[package]
name = "todc-sm"
version = "0.1.0"
edition = "2018"

[dependencies]
num = "0.4"

[dev-dependencies]
todc-utils = { path = "../todc-utils" }
criterion = "0.4"

[target.'cfg(loom)'.dependencies]
loom = "0.5"

[[bench]]
name = "compare_snapshot_implementations"
harness = false

